### ISSUE TITLE
out of box sdk sample failure

### ISSUE THREAD

**Issue by drdbkarron** [Logitech/logi_craft_sdk#11]
I build the craft sdk, registered the .exe in the plugin manager (app manager) but it don't werk.
Yes, i'm running Windows 10 Developer Mode Creator Update and its current, 64 bit.
Should I check if the fireall is burning? I would get a notice if the port was blocked or not approved.

What am i doing to deserve such stonewalling by your plugin manager. I decided to stop plugging and complain to someone.

In the mean time my app is sorely in need of precision rotary controllers.

dB

7/20/2018 6:46:06 AM|Fatal|WebSocket.Connect|WebSocketSharp.WebSocketException: An exception has occurred while reading an HTTP request/response. ---> System.IO.EndOfStreamException: The header cannot be read from the data source.
                              at WebSocketSharp.HttpBase.<>c__DisplayClass1.<readHeaders>b__0(Int32 i)
                              at WebSocketSharp.Ext.EqualsWith(Int32 value, Char c, Action`1 action)
                              at WebSocketSharp.HttpBase.readHeaders(Stream stream, Int32 maxLength)
                              at WebSocketSharp.HttpBase.Read[T](Stream stream, Func`2 parser, Int32 millisecondsTimeout)
                              --- End of inner exception stack trace ---
                              at WebSocketSharp.HttpBase.Read[T](Stream stream, Func`2 parser, Int32 millisecondsTimeout)
                              at WebSocketSharp.HttpRequest.GetResponse(Stream stream, Int32 millisecondsTimeout)
                              at WebSocketSharp.WebSocket.sendHttpRequest(HttpRequest request, Int32 millisecondsTimeout)
                              at WebSocketSharp.WebSocket.sendHandshakeRequest()
                              at WebSocketSharp.WebSocket.doHandshake()
                              at WebSocketSharp.WebSocket.connect()
7/20/2018 6:46:06 AM|Error|WebSocket.Send|This operation isn't available in: closed

**Comment by naokihada** [comment]
@drdbkarron 

I had quick test and verified that it is working.
But I have modified one step from instruction.
  https://github.com/Logitech/logi_craft_sdk/blob/master/samples/WinFormsCrownSample/README.md

ReadMe: "WebSocketSharp" ver 1.0.3 rc11  158k downloaded

I did: "WebSocketSharpFork".  ver 1.0.4 50.6k downloaded
  Above version was not available.
  I thought this is the successor project.

Which "WebSocketSharp" library project did you use?
If it was not same as above, please try with "WebSocketSharpFork".

Attached screenshot is the workings state:

![capture_20180720_115130](https://user-images.githubusercontent.com/7408064/43020031-a0ba8626-8c13-11e8-9d6a-f7703fc1aeeb.png)

Thank you,
Naoki
